spring.application.name=InventoryManagementSystem-ApiGateway

server.port = 9999

eureka.client.service-url.defaultZone = http://localhost:8761/eureka/

# This is basically Spring-cloud API gateway not normal one.
# It offers dynamic routing, request manipulation, and resiliency via predicates/filters
spring.cloud.gateway.server.webflux.discovery.locator.enabled= true

spring.cloud.gateway.server.webflux.discovery.locator.lower-case-service-id= true


#Definig multiple services in API gateway in an orderly manner
spring.cloud.gateway.server.webflux.routes[0].id=inventorymanagementsystem-product
spring.cloud.gateway.server.webflux.routes[0].uri=lb://INVENTORYMANAGEMENTSYSTEM-PRODUCT
spring.cloud.gateway.server.webflux.routes[0].predicates[0]=Path=/productapi/**


spring.cloud.gateway.server.webflux.routes[1].id=inventorymanagementsystem-inventory
spring.cloud.gateway.server.webflux.routes[1].uri=lb://INVENTORYMANAGEMENTSYSTEM-INVENTORY
spring.cloud.gateway.server.webflux.routes[1].predicates[0]=Path=/inventoryapi/**


spring.cloud.gateway.server.webflux.routes[2].id=inventorymanagementsystem-order
spring.cloud.gateway.server.webflux.routes[2].uri=lb://INVENTORYMANAGEMENTSYSTEM-ORDER
spring.cloud.gateway.server.webflux.routes[2].predicates[0]=Path=/orderapi/**




