spring.application.name=InventoryManagementSystem-Server

server.port = 8761

#eureka properties
# it hleps the eureka server not to behave as client and do not register because it is the actual eureka server
eureka.client.register-with-eureka= false
#do not let other registeries to fetch this server .
eureka.client.fetch-registry= false 
